<?php namespace ProcessWire;

/**
 * Process Page Redirects
 *
 * #pw-summary Lists the redirects enabled/created by the PagePathHistory module.
 *
 * @copyright 2023 NB Communication Ltd
 *
 * @todo See if htaccess can be parsed to produce a list of those redirects too
 * @todo Add a simple text filter to the table
 *
 */

class ProcessPageRedirects extends ProcessPageEdit {

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return [
			'title' => 'Process Page Redirects',
			'summary' => 'Lists the redirects enabled/created by the PagePathHistory module.',
			'version' => 200,
			'author' => 'Chris Thomson (NB Communication)',
			'icon' => 'share',
			'permission' => 'page-edit-redirects',
			'requires' => 'ProcessWire>=3.0.225,PHP>=8.1,PagePathHistory',
			'page' => [
				'parent' => 'page',
				'name' => 'redirects',
				'title' => 'Redirects',
			],
		];
	}

	/**
	 * Initialize the module
	 *
	 */
	public function init() {

	}

	/**
	 * List the pages
	 *
	 * @return string
	 * @throws WireException
	 *
	 */
	public function execute() {

		$database = $this->wire()->database;
		$hasLanguagePageNames = $this->wire()->modules->isInstalled('LanguageSupportPageNames');

		$th = [
			$this->_('Redirect Path'),
			$this->_('Destination'),
		];

		if($hasLanguagePageNames) {
			$th[] = $this->_('Language');
		}

		$th[] = $this->_('Created');

		$table = $this->wire()->modules->get('MarkupAdminDataTable');
		$table->setEncodeEntities(false);
		$table->headerRow($th);

		$query = $database->query("SELECT * FROM `page_path_history` ORDER BY `created` DESC");

		$c = 0;
		foreach($query->fetchAll(\PDO::FETCH_ASSOC) as $row) {

			$page = $this->wire()->pages->get($row['pages_id']);
			if(!$page->id || !$page->viewable()) continue;

			$tr = [
				"<a href={$row['path']} target=_blank title='Test this redirect'>{$row['path']}</a>",
				"<a href=$page->editURL#ProcessPageEditSettings target=_blank title='Edit this page'>$page->url</a>",
			];

			if($hasLanguagePageNames) {
				$tr[] = $this->wire()->languages->get($row['language_id'])->title;
			}

			$tr[] = "<span data-uk-tooltip='title:{$this->wire()->datetime->relativeTimeStr($row['created'])}'>{$row['created']}</span>";

			$table->row($tr);
			$c++;
		}

		$this->headline(sprintf($this->_('Page Redirects (%d)'), $c));

		return $table->render();
	}

	/**
	 * Install ProcessPageRedirects
	 *
	 */
	public function ___install() {
		parent::___install();
	}

	/**
	 * Uninstall ProcessPageRedirects
	 *
	 */
	public function ___uninstall() {
		parent::___uninstall();
	}
}
